[package]
name = "day_7_part_2"
version = "0.1.0"
authors = ["BigBlue <shenpaiwilliam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
input_parser = { path = "../../input_parser"}
